:spring_version: current
:toc:
:project_id: gs-rest-service
:icons: font
:source-highlighter: prettify

== What It Is

A service that will accept HTTP GET requests at
`http://localhost:8080/greeting`.

It will respond with a JSON representation of a greeting, as the following listing shows:

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

You can customize the greeting with an optional `name` parameter in the query string, as
the following listing shows:

====
[source,text]
----
http://localhost:8080/greeting?name=User
----
====

The `name` parameter value overrides the default value of `World` and is reflected in the
response, as the following listing shows:

====
[source,json]
----
{"id":1,"content":"Hello, User!"}
----
====

== What You Need

:java_version: 17.0.2
:linkattrs:

ifndef::java_version[:java_version: 1.8]

* A favorite text editor or IDE
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK {java_version}] or later
* http://www.gradle.org/downloads[Gradle 4+] or http://maven.apache.org/download.cgi[Maven 3.2+]


== What It Does

The service will handle `GET` requests for `/greeting`, optionally with a `name` parameter
in the query string. The `GET` request should return a `200 OK` response with JSON in the
body that represents a greeting. It should resemble the following output:

====
[source,json]
----
{
    "id": 1,
    "content": "Hello, World!"
}
----
====

The `id` field is a unique identifier for the greeting, and `content` is the textual
representation of the greeting.

To model the greeting representation, it uses a resource representation class. It
provides a plain old Java object with fields, constructors, and accessors for the `id` and
`content` data, as the following listing (from
`src/main/java/com/example/restservice/Greeting.java`) shows:

====
[source,java]
----
include::src/main/java/com/example/restservice/Greeting.java[]
----
====

NOTE: This application uses the https://github.com/FasterXML/jackson[Jackson JSON] library to
automatically marshal instances of type `Greeting` into JSON. Jackson is included by default by the web starter.

In Spring's approach to building RESTful web services, HTTP requests are handled by a
controller. These components are identified by the
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]
annotation, and the `GreetingController` shown in the following listing (from
`src/main/java/com/example/restservice/GreetingController.java`) handles `GET` requests
for `/greeting` by returning a new instance of the `Greeting` class:

====
[source,java]
----
include::src/main/java/com/example/restservice/GreetingController.java[]
----
====

This controller is concise and simple, but there is plenty going on under the hood. We
break it down step by step.

The `@GetMapping` annotation ensures that HTTP GET requests to `/greeting` are mapped to the `greeting()` method.

NOTE: There are companion annotations for other HTTP verbs (e.g. `@PostMapping` for POST). There is also a `@RequestMapping` annotation that they all derive from, and can serve as a synonym (e.g. `@RequestMapping(method=GET)`).

`@RequestParam` binds the value of the query string parameter `name` into the `name`
parameter of the `greeting()` method. If the `name` parameter is absent in the request,
the `defaultValue` of `World` is used.

The implementation of the method body creates and returns a new `Greeting` object with
`id` and `content` attributes based on the next value from the `counter` and formats the
given `name` by using the greeting `template`.

A key difference between a traditional MVC controller and the RESTful web service
controller shown earlier is the way that the HTTP response body is created. Rather than
relying on a view technology to perform server-side rendering of the greeting data to
HTML, this RESTful web service controller populates and returns a `Greeting` object. The
object data will be written directly to the HTTP response as JSON.

This code uses Spring
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]
annotation, which marks the class as a controller where every method returns a domain
object instead of a view. It is shorthand for including both `@Controller` and
`@ResponseBody`.

The `Greeting` object must be converted to JSON. Thanks to Spring's HTTP message converter
support, you need not do this conversion manually. Because
https://github.com/FasterXML/jackson[Jackson 2] is on the classpath, Spring's
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/http/converter/json/MappingJackson2HttpMessageConverter.html[`MappingJackson2HttpMessageConverter`]
is automatically chosen to convert the `Greeting` instance to JSON.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/spring-boot-application-new-path.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]

`@SpringBootApplication` is a convenience annotation that adds all of the following:

- `@Configuration`: Tags the class as a source of bean definitions for the application
context.
- `@EnableAutoConfiguration`: Tells Spring Boot to start adding beans based on classpath
settings, other beans, and various property settings. For example, if `spring-webmvc` is
on the classpath, this annotation flags the application as a web application and activates
key behaviors, such as setting up a `DispatcherServlet`.
- `@ComponentScan`: Tells Spring to look for other components, configurations, and
services in the `com/example` package, letting it find the controllers.

The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an
application. Did you notice that there was not a single line of XML? There is no `web.xml`
file, either. This web application is 100% pure Java and you did not have to deal with
configuring any plumbing or infrastructure.

== Run the Application

You can run the application from the command line with Gradle or Maven. 

If you use Gradle, you can run the application by using:

====
[subs="attributes", role="has-copy-button"]
----
./gradlew bootRun
----
====

If you use Maven, you can run the application by using: 

====
[subs="attributes", role="has-copy-button"]
----
./mvnw spring-boot:run
----
====

=== Build an executable JAR

:linkattrs:

You can also build a single executable JAR file that contains all the necessary dependencies, classes, and resources and run that. Building an executable jar makes it easy to ship, version, and deploy the service as an application throughout the development lifecycle, across different environments, and so forth.

If you use Gradle, you can build the JAR file by using `./gradlew build` and then run the JAR file, as follows:

====
[subs="attributes", role="has-copy-button"]
----
java -jar build/libs/{project_id}-0.1.0.jar
----
====

If you use Maven, you can build the JAR file with `./mvnw clean package` and then run the JAR file, as follows:

====
[subs="attributes", role="has-copy-button"]
----
java -jar target/{project_id}-0.1.0.jar
----
====

NOTE: The steps described here create a runnable JAR. You can also link:/guides/gs/convert-jar-to-war/[build a classic WAR file].

Logging output is displayed. The service should be up and running within a few seconds.


== Test the Service

Now that the service is up, visit `http://localhost:8080/greeting`, where you should see:

====
[source,json]
----
{"id":1,"content":"Hello, World!"}
----
====

Provide a `name` query string parameter by visiting
`http://localhost:8080/greeting?name=User`. Notice how the value of the `content`
attribute changes from `Hello, World!` to `Hello, User!`, as the following listing shows:

====
[source,json]
----
{"id":2,"content":"Hello, User!"}
----
====

This change demonstrates that the `@RequestParam` arrangement in `GreetingController` is
working as expected. The `name` parameter has been given a default value of `World` but
can be explicitly overridden through the query string.

Notice also how the `id` attribute has changed from `1` to `2`. This proves that you are
working against the same `GreetingController` instance across multiple requests and that
its `counter` field is being incremented on each call as expected.
